# Mod info
mod_name=Iron Door Key
mod_jar_name=IronDoorKey
mod_id=irondoorkey
mod_group=net.mt1006.irondoorkey
mod_author=mt1006
version=1.2.1
license=LGPL-3.0-only
homepage=https://modrinth.com/mod/iron-door-key
source_url=https://github.com/mt1006/mc-irondoorkey-mod
issue_tracker=https://github.com/mt1006/mc-irondoorkey-mod/issues
mod_description=Adds iron door key. It can be used to open iron doors and trapdoors.

# Minecraft and Java
minecraft_version=26.1
java_version=25

# Requires
version_range_fabric=>=26.1
version_range_neoforge=[26.1,)

# Loaders
# https://github.com/FabricMC/fabric-loader/releases
# https://modrinth.com/mod/fabric-api/versions?c=release
# https://projects.neoforged.net/neoforged/neoforge
fabric_loader_version=0.18.4
fabric_api_version=0.144.0+26.1
neoforge_version=26.1.0.1-beta

# Gradle dependencies
# https://github.com/FabricMC/fabric-loom/releases
# https://projects.neoforged.net/neoforged/ModDevGradle
fabric_loom_version=1.15-SNAPSHOT
neoforge_moddev_version=2.0.141

# Gradle configuration
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.problems.report=false
